---
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Project Instructions  

## Overall Goal

Vignettes are explanations of some concept, package, etc. with text, code, and output interweaved.  They generally show their reader how to accomplish some task and/or use functions appropriately. Here are a few examples of varying quality (the first being especially relevant):  

- [NHL API](https://jkclem.github.io/nhl-api-vignette/)
- [Basic Logistic Regression](https://rpubs.com/jared/logistic_regression)
- [Cross Validation](https://cran.r-project.org/web/packages/groupdata2/vignettes/cross-validation_with_groupdata2.html)

We already know how to make vignettes with R Markdown!

Our goal with this project is to create a vignette about contacting an API using functions you've created to query, parse, and return well-structured data.  You'll then use your functions to obtain data from the API and do some exploratory data analysis.

## Creating Your Vignette via R Markdown

You should create a `.Rmd` file that will generate your vignette. When you knit your `.Rmd` file, use the output type `html_document`.  You'll turn both of these files in as your submission for this assignment.

- Your code chunks should be shown in the final document unless they are set up chunks or other behind the scenes things that aren't important.  

## Vignette Content Details  

You are going to create a vignette for reading and summarizing data from an API of your choice. A few examples are listed below but feel free to find one yourself! Please check the required components of the EDA before choosing your API and endpoints to return to make sure all items can be accomplished with the data you collect.

- Financial data: https://polygon.io/docs/getting-started
- NASA data: https://api.nasa.gov/index.html
    + There are a lot of APIs here.  Some easier to deal with than others.
- Beer data: https://www.openbrewerydb.org/documentation
- Pokemon data: https://pokeapi.co/
- Marvel comics data (I'm not sure how much numeric data is here, but there may be some): https://developer.marvel.com/docs
- Movie data: http://www.omdbapi.com/
- Food data: https://spoonacular.com/food-api/docs

The following components must be present in your vignette:  

- You should have a section that notes the required packages needed to use the functions you write

- You should write function(s) to contact your chosen API and return **well-formatted, parsed data in the form of data frame(s) or tibbles**.

    + You do not need to allow the user to query all parts of your chosen API.
    + Your function(s) should allow the user to contact at least one API end point (base URL) and customize that query
    + In total, your function(s) should be able to contact six endpoints or provide for six modifications.
        - This could be two endpoints with 5 modifications on one and none on the other
        - Or three total end points with two modifications on each, etc.
        - For instance, if there is a date modification and a region modification on an end point that you allow the user to use with your function, that would be one end point with two modifications.
    + The function(s) should be user friendly.  That is, it should be easy to specify these end points or modificaitons from the user side.  For example, the ticker types for the financial API has options you can specify such as:
    
        * ADR (American Depository Receipt)
        * CEF (Closed-End Fund)
        * CS (Common stock)
        
    The user shouldn't be required to use the abbreviation and should be able to use the quoted string for use-ability. 
    
- Once you have the function(s) to query the data, you should perform a basic EDA.  Not all things reported need to show something interesting or meaningful (i.e. graphs that show no relationship are fine) but each graph should make sense to look at and **each graph should be discussed.  There should be a narrative throughout your entire document, including your EDA!** 

- A few requirements about your EDA are below:  

    + You should pull data from at least two calls to your API function(s) (possibly combining them into one)
    + You should create at least one new variable that is a function of other variables you collect
    + You should create some contingency tables
    + You should create numerical summaries for some quantitative variables at each setting of some of your categorical variables
    + You should create at least five plots utilizing coloring, grouping, etc.  All plots should have nice labels and titles
         - You should have at least one bar plot, one histogram, one box plot, and one scatter plot

## Submission

You should submit both your `.Rmd` and rendered `.html` files.

# Rubric for Grading (total = 100 points)

Item                                         | Points | Notes  
---------------------------------|-----|---------------------------
Use of proper markdown things such as headings, chunk options, links, etc. | 10      | Worth either 0, 4, 8, or 10  
Required packages list | 4 | Worth either 0 or 4  
Functions to query endpoints | 32  | Worth either 0, 8, 16, 24, or 32   
Creation of relevant new variable(s)         | 6      |  Worth either 0, 3, or 6  
Contingency tables | 8 | Worth either 0, 4, or 8   
Numerical summaries across variables | 12 | Worth either 0, 4, 8, or 12   
Plots | 28 | Worth either 0, 4, 8, ..., or 28   

Notes on grading:  

- For each item in the rubric, your grade will be lowered one level for each each error (syntax, logical, or other) in the code and for each required item that is missing or lacking a description/discussion.
- You should use Good Programming Practices (GPP) when coding.  If you do not follow GPP you can lose up to 50 points on the project.
- If you don't have a narrative or the narrative is lacking you may lose up to 50 points.